### ISSUE TITLE
Put `web.izk-arcos.nl` on landing page

### ISSUE THREAD

**Issue by eversiege** [IzK-ArcOS/ArcOS-Landing-v1#2]
Currently awaiting moving to new domain, after that done, offer users on landing to use web interface. Prioritise recommending to download Electron solution. Helps enhancing attention-span for users coming from websites like MadeWithSvelte.com.

**Comment by IzKuipers** [comment]
Proposing deadline for this change: Sunday August 13th 2023

**Comment by IzKuipers** [comment]
Moving deadline back to Friday August 18th 2023

**Comment by IzKuipers** [comment]
Pushback to August 24th 2023
